
package com.thalesgroup.rtti._2014_02_20.ldb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-28T21:02:03.582Z
 * Generated source version: 3.0.3
 * 
 */
public final class LDBServiceSoap_LDBServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://thalesgroup.com/RTTI/2014-02-20/ldb/", "ldb");

    private LDBServiceSoap_LDBServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Ldb.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Ldb ss = new Ldb(wsdlURL, SERVICE_NAME);
        LDBServiceSoap port = ss.getLDBServiceSoap();  
        
        {
        System.out.println("Invoking getArrivalBoard...");
        com.thalesgroup.rtti._2014_02_20.ldb.GetBoardRequestParams _getArrivalBoard_parameters = null;
        com.thalesgroup.rtti._2014_02_20.ldb.StationBoardResponseType _getArrivalBoard__return = port.getArrivalBoard(_getArrivalBoard_parameters);
        System.out.println("getArrivalBoard.result=" + _getArrivalBoard__return);


        }
        {
        System.out.println("Invoking getDepartureBoard...");
        com.thalesgroup.rtti._2014_02_20.ldb.GetBoardRequestParams _getDepartureBoard_parameters = null;
        com.thalesgroup.rtti._2014_02_20.ldb.StationBoardResponseType _getDepartureBoard__return = port.getDepartureBoard(_getDepartureBoard_parameters);
        System.out.println("getDepartureBoard.result=" + _getDepartureBoard__return);


        }
        {
        System.out.println("Invoking getArrivalDepartureBoard...");
        com.thalesgroup.rtti._2014_02_20.ldb.GetBoardRequestParams _getArrivalDepartureBoard_parameters = null;
        com.thalesgroup.rtti._2014_02_20.ldb.StationBoardResponseType _getArrivalDepartureBoard__return = port.getArrivalDepartureBoard(_getArrivalDepartureBoard_parameters);
        System.out.println("getArrivalDepartureBoard.result=" + _getArrivalDepartureBoard__return);


        }
        {
        System.out.println("Invoking getServiceDetails...");
        com.thalesgroup.rtti._2014_02_20.ldb.GetServiceDetailsRequestParams _getServiceDetails_parameters = null;
        com.thalesgroup.rtti._2014_02_20.ldb.ServiceDetailsResponseType _getServiceDetails__return = port.getServiceDetails(_getServiceDetails_parameters);
        System.out.println("getServiceDetails.result=" + _getServiceDetails__return);


        }

        System.exit(0);
    }

}
